### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by phillipdwright** [CiscoPSIRT/openVulnAPI#41]
This is a request for Python 3 support for this tool. There are a few incompatibilities, but they seem fairly minor.

**Comment by phillipdwright** [comment]
I'd be interested in helping with this, if you're open to outside contributions.

**Comment by fgs-pwright** [comment]
Is there any interest in this?  I would like to use this API wrapper from within a project written to target Python 3.6.

**Comment by santosomar** [comment]
Thank you for your contribution @phillipdwright ! I have approved your pull request!

**Comment by isidrov** [comment]
I am having issues to run it on python3. I understand the issue is still open? 

Traceback (most recent call last):
  File "/usr/local/bin/openVulnQuery", line 11, in <module>
    load_entry_point('OpenVulnQuery==1.26', 'console_scripts', 'openVulnQuery')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/openVulnQuery/main.py", line 4, in <module>
    import config
ImportError: No module named 'config'

**Comment by phillipdwright** [comment]
@isidrov Did you install using pip? It looks like [the version of this package on PyPI](https://pypi.python.org/pypi/OpenVulnQuery/1.26) does not have the latest changes. You may need to download it directly from GitHub to use it with Python 3.5.

**Comment by waukeerules** [comment]
Does openVulnAPI work with Python 3.6.5? I haven't been able to get the module to load properly using pip.

**Comment by phillipdwright** [comment]
@waukeerules If you just do `pip install openVulnQuery`, you'll be installing from PyPI, which looks to be an old version before Python 3 compatibility was established. You could download the latest code directly from GitHub and install it as downloaded, if you needed Python 3 compatibility.

**Comment by waukeerules** [comment]
Thank you @phillipdwright. I was able to get the latest code installed by running `python setup.py install`. I did this yesterday, but I didn't think it worked because the documentation I was following was outdated or misleading. 

#OLD SYNTAX - Does not work.
query_client = query_client.QueryClient(client_id="", client_secret="")

#NEW SYNTAX - Works
query_client = query_client.OpenVulnQueryClient(client_id="", client_secret="")

**Comment by santosomar** [comment]
Thank you @waukeerules ! I just updated the query_client documentation in the README via 
https://github.com/CiscoPSIRT/openVulnAPI/commit/46b162de70183550572235db80f701b318fafcb2
